# Generated by Django 4.2.21 on 2025-05-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='main_app_or_order_i_f18740_idx'),
        ),
    ]
